### PR TITLE
Reenable and fix add-, edit-, and delete dashboard

### PR DESCRIPTION
**Pull request by jpkeyw**
I left the buttons where they were. Moving them is minor. Some of the functionality had been broken, so I fixed that, too, when I uncommented the button code. Also, the "add" never worked due to it missing the content-type header. And, after deletion, the app died because it was not fixing the URL.

### CODE REVIEW

**Comment by jeffshaver** [comment]
@jpkeyw technically, since these aren't "functional" yet (you can't add visualizations to them, etc...) ,they should remain disabled. They just needed be fixed so that they don't fall to far out of date.

**Comment by jpkeyw** [comment]
Ability to add visualizations is next on my list. I'll stay on this branch to add that code. (First iteration will simply allow adding existing visualizations to a dashboard.)

**Comment by jeffshaver** [comment]
@jpkeyw make sure you keep the branch up-to-date by rebasing often.

**Comment by jpkeyw** [comment]
Yup. I'm still working on this branch with the modifications and additions for "add an existing viz to a dashboard" story.

**Pull request closed without merging**
