### PR TITLE
Closes #192. Show error messages

### LINKED ISSUE #192: Show relevant error messages
Error messages from the REST service are not being displayed. The error message needs to be pulled from the response.

### PR DESCRIPTION
**Pull request by knorris**

### CODE REVIEW

**Comment by jeffshaver** [comment]
Won't this need to come alongside some changes to `App.jsx`?

**Comment by knorris** [comment]
No. Since an object is created for an error in fetchChekcStatus(), App.jsx is fine.

**Comment by jeffshaver** [comment]
@knorris yeah, but now its displaying Network Error: <your error> instead of just the error.

**Comment by knorris** [comment]
There are also changes on the REST side too. So, you need both.

**Comment by jeffshaver** [comment]
@knorris `App.jsx` literally puts `Network Error` in the message on the screen on purpose (https://github.com/jeffshaver/safe-app/blob/dev/src/js/components/App.jsx#L71). Since we had almost no error messages, that is what was put there. if we are going to do better errors on the rest side, than we can just display the errors that we get instead of interpreting them on the client.

**Pull request merged**
